repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: detect-aws-credentials
  - repo: https://github.com/prettier/prettier
    rev: 1.16.2
    hooks:
      - id: prettier
